version: '3.6'
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - './config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    ports:
      - '1883:1883'
      - '8000:8000'
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquitto
    environment:
      - 'mqtt:host=mosquitto'
      - 'mqtt:clientId=ResultsService'

      - 'ola:database:server=192.168.10.136'
      - 'ola:database:database=ola'
      - 'ola:database:username=TvService'
      - 'ola:database:password=secret'
      - 'ola:eventid=1'
      - 'ola:eventraceid=1'
    ports:
      - '8080:80'
    volumes:
      - './service-logs:/app/logs'
  layout-service:
    build:
      context: ./layout-service
      dockerfile: Dockerfile
    restart: always
    environment:
      - 'database:server=192.168.10.136'
      - 'database:database=layout'
      - 'database:username=layout-service'
      - 'database:password=secret'
    ports:
      - '8081:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquitto
    environment:
      - 'mqtt_host=results'
      - 'mqtt_port=8000'
      - 'results_rest_host=results'
      - 'results_rest_port=8080'
      - 'layouts_rest_host=results'
      - 'layouts_rest_port=8081'
    ports:
      - '80:80'
