version: '3.6'
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - './config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    ports:
      - '1883:1883'
      - '8000:8000'
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquitto
    environment:
      - 'mqtt:host=mosquitto'
      - 'mqtt:clientId=ResultsService'
      - 'database:server=192.168.10.136'
      - 'database:database=tt2017'
      - 'database:username=TvService'
      - 'database:password=secret'
      - 'database:competition=3'
      - 'database:stage=3'
    ports:
      - '8080:80'
    volumes:
      - './service-logs:/app/logs'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquitto
    volumes:
      - './config/client.json:/usr/share/nginx/html/config.json'
    ports:
      - '80:80'
