version: '3.1'
services:
  mysql:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password --lower_case_table_names=1'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: OLA
      MYSQL_USER: TvService
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - './sql-init:/docker-entrypoint-initdb.d'
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - './config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    ports:
      - '1883:1883'
      - '8000:8000'
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - mosquitto
    environment:
      - 'mqtt:host=mosquitto'
      - 'mqtt:clientId=ResultsService'
      - 'system=ola' # ola meos

      - 'ola:database:server=mysql'
      - 'ola:database:database=ola'
      - 'ola:database:username=TvService'
      - 'ola:database:password=secret'
      - 'ola:eventid=1'
      - 'ola:eventraceid=1'

      - 'meos:database:server=mysql'
      - 'meos:database:database=ola'
      - 'meos:database:username=TvService'
      - 'meos:database:password=secret'
    ports:
      - '8080:80'
    volumes:
      - './service-logs:/app/logs'
  layout-service:
    build:
      context: ./LayoutService
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/layout'
      - 'SPRING_DATASOURCE_USERNAME=layout-service'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    ports:
      - '8081:8081'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquitto
    environment:
      - 'mqtt_host=results'
      - 'mqtt_port=8000'
      - 'results_rest_host=localhost'
      - 'results_rest_port=8080'
      - 'layouts_rest_host=localhost'
      - 'layouts_rest_port=8081'
    ports:
      - '80:80'
