version: '3.1'
services:
  mysql:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password --lower_case_table_names=1'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: OLA
      MYSQL_USER: TvService
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - './sql-init:/docker-entrypoint-initdb.d'
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - './config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    ports:
      - '1883:1883'
      - '8000:8000'
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - mosquitto
    environment:
      - 'mqtt:host=mosquitto'
      - 'mqtt:clientId=ResultsService'
      - 'database:server=mysql'
      - 'database:database=ola'
      - 'database:username=TvService'
      - 'database:password=secret'
      - 'database:competition=1'
      - 'database:stage=1'
    ports:
      - '8080:80'
    volumes:
      - './service-logs:/app/logs'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquitto
    ports:
      - '80:80'
