version: '3.1'
services:
  mysql:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: OLA
      MYSQL_USER: TV
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - './sql-init:/docker-entrypoint-initdb.d'
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
    ports:
      - '1883:1883'
      - '8000:8000'
  tv-service:
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - mosquitto
    environment:
      - 'mqtt:host=mosquitto'
      - 'database:server=mysql'
      - 'database:database=tt2017'
    volumes:
      - './cs-logs:/app/logs'
    ports:
      - '80:80'
      - '8080:8080'
